### ISSUE TITLE
Tags overlapping text on hover

### ISSUE THREAD

**Issue by zvikarp** [dailynowco/daily#121]
#### Bug Report

Explanation: when hovering over a card, if there is a lot of text and a lot of tags they overlap as shown in the screenshot. maybe maxing the text to 3 links and the tags to 2 lines and using ellipsis.

Version: *Daily version 2.10.0

Browser version: Version 78.0.3904.97 (Official Build) (64-bit)

OS: Windows 10

![image](https://user-images.githubusercontent.com/13397207/69155829-1d192180-0aeb-11ea-9cae-cbed21d05805.png)

**Comment by idoshamun** [comment]
Hi @zvikarp,

Thank you for submitting this bug report and for keeping being active in this project. It means a lot 🤩.
We already solved this bug in version 2.10.1, please try to update Daily and let me know if the issue is indeed solved.
Hopefully, you are also enjoying the brand new search feature.

**Comment by zvikarp** [comment]
👍 sorry next time I'll check I'm up to date.

**Comment by idoshamun** [comment]
No worries, feel free to reach out :)
