### ISSUE TITLE
[Question] Why not add extension content into website?

### ISSUE THREAD

**Issue by Olyno** [dailynowco/daily#123]
#### Feature Suggestion

Hi,
The current extension is pretty nice, but I got a question: why I must (and any other devs) install the extension to get access to the content? Your extension could be so famous in dev communities if it was a website, so why don't you add the extension content on the current website?

**Comment by idoshamun** [comment]
Hi @Olyno,
Thank you for showing interest in Daily.
Currently, we believe a New Tab extension is the best way to consume dev news.
This implementation makes the reader a passive content consumer rather than actively pursuing for news.
With that said, we do have a standalone webapp in our future roadmap but probably we have a long way to go.

**Comment by Olyno** [comment]
A new tab could be a website. I mean, if you did it as extension, I hope you can make it a website as ``dev.to``

**Comment by idoshamun** [comment]
Yes, the extension is indeed developed as a website but still, there are some adaptations required.
As mentioned, we have it on our roadmap but will take some time :)

**Comment by Olyno** [comment]
Sure. Anyway, thanks for your answer :)
