### ISSUE TITLE
unable to sync my saved posts accross browsers

### ISSUE THREAD

**Issue by Bharat-Vadivelu** [dailynowco/daily#129]
I am unable to see the same saved posts accross different machines. My saved posts are also lost once i relogin in a device.

**Comment by idoshamun** [comment]
Hi @Bharat-Vadivelu,

Unfortunately, we had an issue with our API service for a few minutes. Please check again to see if now your issue is resolved.
Once you save bookmarks when you are logged-in, these bookmarks should be there for you all the time across all devices, even if you re-login.
When you re-login make sure you use the same login provider (Google/Twitter) as you originally used.

I'm looking forward to your response.

**Comment by Bharat-Vadivelu** [comment]
Hi @idoshamun,
Now everything is working as expected. Thanks for the quick response.

**Comment by idoshamun** [comment]
Awesome! I'm glad to hear :)
