### ISSUE TITLE
🐛 BUG: Article comments appear as article?

### ISSUE THREAD

**Issue by marik22312** [dailynowco/daily#132]
### What went wrong? 🤔

One of the featured articles is actually a comment to an article,

### Expected Behavior

I expected the tiles to lead to articles, not to article comments

### Actual Behavior

On the articles list, sometimes the articles are comments to articles.
example url: https://app.dailynow.co/r/4887690d3b1ff225dff26373dcbd3029

### Steps to Reproduce Issue

Don't know how to reproduce, but one of 

#### Operating System
Mac OS Mojave

#### Version of Daily
2.12.2

#### Browser

Chrome 79.0.3945.117

**Comment by DamianoMagrini** [comment]
I can confirm that the issue is present, but maybe it would be better suited for [daily/daily-api](https://github.com/dailynowco/daily-api)? Someone with write access may want to transfer this issue to that repo.

**Comment by marik22312** [comment]
@DamianoMagrini It's probably more suited there... TBH I didn't checkout what other repos they have...

**Comment by idoshamun** [comment]
Hi @marik22312,
Thanks for reporting this issue.
We fetch content from Medium using their RSS feed, I will have to dig in deeper to understand why they put comments as well.
By the way, don't worry about the different repos. This is the best place for submitting any issue.

**Comment by idoshamun** [comment]
If anyone has any idea about how to filter out comments from medium's rss, I would be great :pray:

**Comment by DamianoMagrini** [comment]
The first close-to-trivial solution would be to weed out every post whose content's length is less than a set number of characters.

Otherwise, I have noticed that Medium's article pages all have a `<script>window.__APOLLO_STATE__ = { /* ... */ }</script>` element. It contains an enormous (easily >100 kB) JSON object which in turn, to my understanding, contains pre-cached GraphQL queries. Among its keys is `Post:whatever-the-post-id`, which is another object (is this getting boring?), among whose keys is `inResponseToPostResult`, which can be either `null` or a string. If it is `null`, then the post is not in response to anything, so it's not a comment. Otherwise, it's set to the id of the post it is in response to, so it *is* a comment.

Adopting the latter method, every article would have to be fetched and parsed, which could be quite compute-intensive — so, eh, maybe the hacky first option is the best to go with. You decide 🤷‍♂️

*(disclaimer: I'm by no means a Medium expert! 😅 So there may very well be better options than these two)*

**Comment by idoshamun** [comment]
@DamianoMagrini awesome ideas, I also noticed the `__APOLLO_STATE__` but I'm afraid it might be subject to changes. Your first idea about the content length is very easy to implement as I'm already crawling for the content to estimate reading time.

**Comment by DamianoMagrini** [comment]
In the meanwhile, I've managed to disable Apollo state caching, so I've been able to see the GraphQL query that returns details about the article — I've copied it [here](https://gist.github.com/DamianoMagrini/bd2288212fe71ad67ee959e9da61bd29) (it's quite long, but most info is useless for Daily's purposes, so it could easily be shrunk by a lot). The query takes in three variables: `postId`, `postMeteringOptions` and `enableThemeEditor` (see gist).

I'm afraid this may be against Medium's terms of use though 😕 (the GraphQL API is private), so it's probably better just to check the length.

**Comment by idoshamun** [comment]
@DamianoMagrini You're truly the best. Eventually, I decided to search for the element in the screenshot below. This is the link to the original article so as long as it's a comment this link must appear.
![Link to main article](https://user-images.githubusercontent.com/1993245/72715516-456bdd80-3b79-11ea-89f7-3a814a08ce24.png)
