### ISSUE TITLE
I need blank space to focus

### ISSUE THREAD

**Issue by MartinMuzatko** [dailynowco/daily#17]
Hello.

I really love how many good resources you bring together here.
However, the app as "new tab" is a complete mind destroyer for me.
It is not about short attention span, but it is a flow-killer. You want to go to a website, and before you can enter the url, which you knew when you created a new tab, all of a sudden you are distracted by the multitude of articles.

I wouldn't mind if I could get dailynowco as an app to open in a separate window. But for every single new tab, this really kills my productivity.

I hope there is an alternative to having dailynowco as new tab.
I want to decide on my own when to browse for news and when to work.

Hope you will find a way, or even better: just offer the articles on your website. Maybe it is just your product strategy to just offer this als new tab app, but this is the worst way for me to consume that content.

By the way, for everyone looking to consume dailynow in another fashion, I found the API endpoint:
https://app.dailynow.co/v1/posts/latest?latest=2018-07-31T14:08:51.422Z&page=0&pageSize=30&pubs=airbnb,alligator,angular,aws,soundcloud,botsfloor,chromium,codeburst,codementor,codrops,css_tricks,daily_js,daily,devto,dev_channel,echojs,facebook_code,freecodecamp,github,gcp,hackernoon,itnext,kdnuggets,k8s,lightbend,linkedin,logrocket,medium_js,hacks,msdn,netflix,nodejs,nodesource,npm,pragmatists,quick_code,risingstack,scotch,sitepen,sitepoint,smashing,softwaremill,spotify,tem,disney,vue,tutorialzine,tuts_plus,twitter,web_fundamentals,webkit

**Comment by idoshamun** [comment]
Hi @MartinMuzatko,

I appreciate your effort to write this valuable feedback.
Currently we are focusing on delivering our value via the extension.
Of course, we also work on other channels as well but the core channel is the extension.

I understand your points but unfortunately I don't have a solution for you. 
You might expect something in the far future.

Regarding the API, we are about to block it for third party access so I wouldn't count it :wink:

**Comment by idoshamun** [comment]
@MartinMuzatko Thank you deeply! 

I am happy to see that you are an experienced developer who is familiar with building reliable APIs.
I don't like the way the conversion turned over. We usually try to satisfy our users but sometimes it just doesn't align with our roadmap. Our time is limited and we can't do everything, I'm sure you realize that.

As of today we are not willing to open our API to public otherwise we would have already done it.
Again, I'm sure you understand how much time it took us and will take to build this product and to make it better.  When the time comes we will open our API as an RSS feed or something else but it is not the time yet.

Let's keep up the good work!

**Comment by ran-eh** [comment]
Add my +1 against Daily monopolizing the new add.  People sensitive to visual noise are a sizable minority, and for us this is unfortunately a show stopper.It is possible that you are concerned about this lowering engagement, so I won't mind if option for turning it off is not easily discoverable, so it is in fact only available  

Options I would like:

* Easy and quick to implement: clicking the extension tag on the browser will enable/disable new tab monopolizing.
* Better, but harder: add the number of new items since last view to the extension icon (for example, see the LinkedIn icon)
![image](https://user-images.githubusercontent.com/39743102/62803860-74493800-baa0-11e9-9edb-a3356b648bcb.png)

**Comment by ran-eh** [comment]
Add my +1 against Daily monopolizing the new tab.  People sensitive to visual noise are a sizable minority, and for us this is unfortunately a show stopper.  I expect your business model is advertisingIt is possible that you are concerned about this lowering engagement, so I won't mind if option for turning it off is not easily discoverable, so it is in fact only available  

Options I would like:

* Easy and quick to implement: clicking the extension tag on the browser will enable/disable new tab monopolizing.
* Better, but harder: add the number of new items since last view to the extension icon (for example, see the LinkedIn icon)
![image](https://user-images.githubusercontent.com/39743102/62803860-74493800-baa0-11e9-9edb-a3356b648bcb.png)

**Comment by ran-eh** [comment]
Ahlan Ido,

I am adding my +1 regarding the monopolizing new tabs.  People sensitive to visual noise are a sizable minority, and for us this is unfortunately a show stopper.

My suggestion: add a no-noise flag setting.  When the flag is on, clicking the extension icon will toggle the new tab functionality on/off.  I expect this would be quick to code, test and deploy.  So impact on dev bandwidth should be minimal.

I am guessing that your business model is advertising based, and you may be concerned that this feature may lower engagement and affect the bottom line.  If this is the case, I suggest making the no-noice feature only discoverable for those who explicitly look for it - on this topic perhaps.

Thanks

-- Ran

P.S. @MartinMuzatko - as a workaround, I created a dedicated chrome profile for this extension, and uninstalled it on my other profiles.  It's a pain for a host of reasons, and I think Daily can and should do better.  However, it's better than nothing.

**Comment by idoshamun** [comment]
Shalom @ran-eh,
Lately we have been 
receiving the same request from many users and even in another issue https://github.com/dailynowco/daily/issues/11 (it's better to move the discussion there).

We do have some progress about this matter, you can take a look here https://github.com/dailynowco/daily/issues/54. It takes a little bit time because this feature is developed by the community rather than us. We also think about another solution which is yet too early to discuss about.
