### ISSUE TITLE
Feature and bug reports.

### ISSUE THREAD

**Issue by lt692** [dailynowco/daily#32]
#### Feature Suggestion

![image](https://user-images.githubusercontent.com/48758376/54684008-c8687580-4b1b-11e9-836a-1952e7cfc02b.png)

Quick links are kinda broken for me (red ink). I would really love that you would add a customizable link menu just here (Blue ink). Green ink plus sign would allow to add new links.

![image](https://user-images.githubusercontent.com/48758376/54684208-4a589e80-4b1c-11e9-8b0f-e7f02900250d.png)

#### Bug Report

Dont know if its a bug or not but.
When you dont hover over text it is normal.
![image](https://user-images.githubusercontent.com/48758376/54684297-99063880-4b1c-11e9-9006-886494fe9d7b.png)
BUT if you do hover over it it becomes bigger and blurry
![image](https://user-images.githubusercontent.com/48758376/54684335-b3401680-4b1c-11e9-89c9-849b90034bfe.png)

#### Feedback

I really enjoy exploring your product! Keep up the good work.

**Comment by idoshamun** [comment]
Hi @lt692,

Thanks for submitting the feature suggestion and bug report.

- I have to investigate deeper regarding the quick links as we use a third party service to provide the icons. I also noticed that this service is not 100% reliable.
- Customizable links is pretty cool, I will raise it in our next product planning.
- The blurry thing is not on purpose but probably because we scale everything, I need to check if there is a way to keep everything sharp.

We are working on Daily 2.0 which should be released very soon with bunch of new features and much more customizations. Stay tuned! (you can subscribe here https://www.producthunt.com/upcoming/daily-2-0)

**Comment by ekfuhrmann** [comment]
I too have noticed that the hover state is quite blurry for the cards. I know that I personally try and avoid using `transform: scale()` on anything containing text for this very reason as it results in blurry copy.

**Comment by idoshamun** [comment]
@ekfuhrmann you are right, this happens because of the scale transformation but this is the best way to create high performance animations. Maybe we should change the animation, I will discuss with the team.

**Comment by hcmlopes** [comment]
I have taken a little time to test some options and the problem is on how the text gets rendered when scaled, however we can increase the scale to **scale(1.08)** which at that point it is acceptable in sharpness.

This amount may be a bit extreme but I feel like its a better experience then the blurry text.

**Comment by idoshamun** [comment]
@hcmlopes thanks for dedicating the time!
I will check it out with our designer and get back to you :)

**Comment by idoshamun** [comment]
I just released version 2.1.1 with `scale(1.02)`.
Hopefully it satisfies your needs, thanks for baring with us :)
